### ISSUE TITLE
Mentions property shared between messages in "messageUpdate" client event

### ISSUE THREAD

**Issue by Orbitalstrikegaming** [hydrabolt/discord.js#1089]
When a message such as "Hi" is edited to "Hi @orbit" the messageUpdate event will show identical message.mentions properties for both newMessage and oldMessage. In this case the expected newMessage.mentions property is used for both.

If "Hi @orbit" is edited to "hi", the newMessage.mentions property will also use the expected oldMessage.mentions object.

Basically if a mention is used in a message, it seems to be shown in all versions of that message, even versions before the mention was edited in.

**Comment by Gawdl3y** [comment]
It doesn't look like #1138 will fix this. To reiterate the issue, in full:
- The `messageUpdate` event's `newMessage` and `oldMessage` parameters will end up sharing the exact same collections, since they're just holding references to the same one.
- `Message#edits` old messages will also be affected, sharing the same collections with the current version of the message.

In order to fix this, an entirely separate Message instance must be copied from the current message prior to applying any updates to the current one. The new copy will be the *old* message. This is what should be emitted in the event as `oldMessage`, and added to `Message#edits`.
