### ISSUE TITLE
I can't Install Discord.js

### ISSUE THREAD

**Issue by rogafe** [hydrabolt/discord.js#110]
//Sorry for my English i am French

The server said: 
npm WARN ENOENT ENOENT: no such file or directory, open '/root/package.json'
npm WARN EPACKAGEJSON root No description
npm WARN EPACKAGEJSON root No repository field.
npm WARN EPACKAGEJSON root No README data
npm WARN EPACKAGEJSON root No license field.

http://i.imgur.com/G4QxK3a.png

**Comment by brussell98** [comment]
Just to make sure, you are running this in the root directory of the bot and it contains a `package.json` file right?
![image](https://cloud.githubusercontent.com/assets/16432550/12012171/c74b5172-acae-11e5-990f-0cc75ce0e3cb.png)

**Comment by abalabahaha** [comment]
Notice the "WARN". It's a warning, but it does not break your installation. Your installation should be fine,

**Comment by TehSeph** [comment]
@rogafe Do `npm init` and follow the steps and fill in the information for your bot, then do `npm i --save discord.js` afterwards. The warnings are because NPM is failing to find a `package.json` file where you are attempting to install the library. The first command will create that file for you using the information you give it. The second command installs the library, like you have already done, but with the `--save` flag which will add it to the file created in the first step. As @abalabahaha said above, the library is installing fine but NPM is warning you that it cannot find a `package.json` file and thus also can't find the 4 fields in the other warnings which are soft-requirements for all public packages.

**Comment by rogafe** [comment]
Thank you all for your reply, I install node Js and everything works
Thanks Rogafe

**Comment by Ediut** [comment]
I'm having issues installing discord.js too. It gives me the same warnings. I tried to use npm init and the other command from Seph but it gives me an error saying "no capital letter can be used" even though there arent caps in it. help pls.
