### ISSUE TITLE
.hasPermission("SEND_MESSAGES") returns the wrong value

### ISSUE THREAD

**Issue by iaace-NA** [hydrabolt/discord.js#1168]
I have a bot on a server which is given a role with SEND_MESSAGES enabled. I also have a channel set up for the bot to send stuff in, so SEND_MESSAGES for that role in this specific channel is explicitly enabled. For this same channel, @everyone's permission for SEND_MESSAGES is explicitly disabled. when I call eval msg.channel.permissionsFor(client.user).hasPermission("SEND_MESSAGES") , it returns false, and sends a message in the same channel, which should not be possible if the return value is false. *edit: it returns true when @everyone's SEND_MESSAGES is explicitly enabled in the channel. It might apply to other permissions too, but this is not something I have tested. tested on v11.0.0 and v11#indev 2/4/2017 UTC 18:15.
![image](https://cloud.githubusercontent.com/assets/23423640/22620498/44651966-eadb-11e6-8f2a-fc6159df4c67.png)

**Comment by meew0** [comment]
This bug is in [`permissionsFor`](https://github.com/hydrabolt/discord.js/blob/master/src/structures/GuildChannel.js#L67): the problem is that rather than first applying all deny overrides and then applying all allow overrides, it applies the first overwrite's deny overrides, then its allow overrides, then the second's deny overrides etc.

**Comment by switz** [comment]
I'm seeing this bug:

```
existingChannel.permissionsFor(client.user).has(Permissions.FLAGS.SEND_MESSAGES)
```

is returning true despite the bot not having permissions in the channel to send messages

**Comment by almostSouji** [comment]
If you can still reproduce a bug from 5 years ago, please open a new issue instead of necro-posting here, so we can track bugs properly.

You generally need permission to view a channel to be able and do anything on it. You can find more information about implicit permissions on our guide at https://discordjs.guide/popular-topics/permissions-extended.html#implicit-permissions
