### ISSUE TITLE
Try to Resume on Disconnect

### ISSUE THREAD

**Issue by bdistin** [hydrabolt/discord.js#1344]
https://github.com/hammerandchisel/discord-api-docs/issues/215

H&C has implemented a max of 1000 new sessions per day before they will reset your token. However, if you resume the connection, it doesn't count against your 1k sessions. Currently in Master, whenever the bot disconnects they will get a new session, rather than trying to resume the session. This means, for every 1006 ect disconnect we get from cloudflare, that can be properly resumed, are counting against our daily login limit.

This has previously been implemented in the internal sharding pr. But is something that probably would benefit being moved to master. And in the internal shading pr, it replays missed events, so if your bot dcs it will catch up on everything it missed during the dc which is also nice.

**Comment by 0xAyam** [comment]
why was it marked as invalid? Looks very legit. What is the correct way of resuming the connection?

**Comment by kyranet** [comment]
> why was it marked as invalid?

Seeing as the author closed the issue, it might be because a misunderstanding on how something worked.

> What is the correct way of resuming the connection?

You don't, Discord already handles that for you.

---

Please do not necro issues/PRs from years ago, discord.js has released dozens of versions since this issue, so it's not longer valid anymore. If you have a similar issue, open a new issue.
