### ISSUE TITLE
Voice connection timeout

### ISSUE THREAD

**Issue by inparsian1** [hydrabolt/discord.js#1662]
**Please describe the problem you are having in as much detail as possible:**
I'm trying to get my music bot to work, first I had an issue with FFMPEG which I fixed, but I seem to have trouble getting around this.

**Include a reproducible code sample here, if possible:**
```js
if(!message.guild.voiceConnection) message.member.voiceChannel.join().then(function(connection) {
			play(connection, message);
		});
```

**The error I get:**
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (C:\Users\nope\Documents\Folders\Atomic\node_modules\discord.js\src\client\voice\VoiceConnection.js:256:26)
    at connectTimeout.client.setTimeout (C:\Users\nope\Documents\Folders\Atomic\node_modules\discord.js\src\client\voice\VoiceConnection.js:277:18)
    at Timeout.setTimeout (C:\Users\nope\Documents\Folders\Atomic\node_modules\discord.js\src\client\Client.js:422:7)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Further details:**
Bot's name is Atomic, it happens when I use the play command on it.

- discord.js version: v11.1.0
- node.js version: v6.10.2
- Operating system: Windows 10

*I tested with the latest master build also.*

**Comment by KyeNormanGill** [comment]
Discord.js requires nodejs version 8.0.0 or higher. Please update node and try again.

**Comment by inparsian1** [comment]
It still works, honestly :P

**Comment by KyeNormanGill** [comment]
What version of d.js are you using

**Comment by inparsian1** [comment]
I'm using the latest version of d.js

**Comment by KyeNormanGill** [comment]
...use `npm ls discord.js` and tell me the version of d.js you are using.

**Comment by inparsian1** [comment]
It says I'm using 11.1.0

**Comment by inparsian1** [comment]
By the way here's the code ``if(!message.guild.voiceConnection) message.member.voiceChannel.join().then(function(connection) {
			play(connection, message);
		});``

**Comment by vzwGrey** [comment]
Under "**Include a reproducible code sample here, if possible:**" you should actually add some *code*, you added an *error*. Obviously that error is helpful as well, but we need a way to actually reproduce that error, so we can actually fix it.

Also, please test your code with the latest master build as well. You can install that using `npm i hydrabolt/discord.js`. Otherwise we'd be trying to fix an error that's already been fixed.

So please edit your original issue with:
* The correct discord.js version instead of just "The latest version"
* Add the code you used (obviously only the relevant part)
* Add a disclaimer you've tested it with the latest master build (obviously only *after* you've actually done that)

**Comment by inparsian1** [comment]
Already edited.

**Comment by inparsian1** [comment]
Resolved, just found some typos in the original code :P
