### ISSUE TITLE
How to make a blacklist based on UserId

### ISSUE THREAD

**Issue by Kiriot22fet** [hydrabolt/discord.js#1935]
I have a selfbot, many people abuse a command of it. (Yes, i made it that can  interact with other users.) But there is a problem.  It does not match for some reason the message.author with the id.

Bande = "<@331416390894354432>"

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by Kiriot22fet** [comment]
I  can't

**Comment by Kiriot22fet** [comment]
I am banned from there for testing my reaction sopam

**Comment by Kiriot22fet** [comment]
when i had an issue of unknown emojis

**Comment by Kiriot22fet** [comment]
so i have no choice

**Comment by iCrawl** [comment]
Okay, so first of all, stop spamming new messages the email notifications of a lot of people will appreciate it.

Second, whats your discord tag + user id.

Third, we do not help now allow any use of a userbot that answers other users outside of the scope of a bot account.

**Comment by Kiriot22fet** [comment]
TEAM RAULIB JOIN TODAY!#4120

**Comment by Kiriot22fet** [comment]
And my selfbot is to be useful in some way to some users.

**Comment by Kiriot22fet** [comment]
I just need to know why it doesn't compare the user with the registered id

**Comment by Kiriot22fet** [comment]
Cause i use a chat logger to monitorize the activity of people who use my selfbot

**Comment by iCrawl** [comment]
You have 3 cases on your belt, all 3 are related to you not listening what we listed there.

Also not mentioning that you are pretty much breaking discord TOS with having a Selfbot running that responds to other users, we told you explicitly before the ban what you should do, but you did not comply.

I don't see how this is going to be resolved any time soon. Again, Selfbots responding to other users are not allowed. It is only allowed to respond to yourself.

You can find more information here:
https://anidiots.guide/examples/selfbots-are-awesome.html

I will lock this thread now because this is not a discussion or help forum.
