### ISSUE TITLE
Bot gives the role, and then removes it

### ISSUE THREAD

**Issue by T1MOXA** [hydrabolt/discord.js#1988]
Bot gives the role, and then removes it (the same role). 
![image](https://user-images.githubusercontent.com/19938629/31049688-bea23f08-a640-11e7-9159-0684a74d3ac3.png)

My code:
```
const Discord = require("discord.js");
const bot = new Discord.Client();

bot.on('ready', () => {
	const guild = bot.guilds.get('249828546153938955');
	const member = guild.member(bot.users.get('146770757463179264'));
	if(member) {
	       member.removeRoles('363796105357557761'); 
               member.addRole('363796178304761866');
	}
});
```

- discord.js version: 11.2.1
- node.js version: 8.4.0
- Operating system: Win10
- Priority this issue should have – I don't know ^_^
If it's bug - may be middle :) 

P.S. On your Discord server did not help me with this issue, so I suspect that is a bug.

**Comment by SpaceEEC** [comment]
Can you please fill out the issue template, especially this part:
![grafik](https://user-images.githubusercontent.com/24881032/31049730-46014d2a-a639-11e7-9899-60ac75e7ca33.png)

**Comment by T1MOXA** [comment]
Sorry, added.

**Comment by SpaceEEC** [comment]
Your issue here is a mixture of a race condition and the how the lib handles removing or adding of multiple roles.

That being: Modifying the cached roles of the member and them patching all of them to the api (Equal to `GuildMember#setRoles`). (lib handling part)

This removes your newly added role, if the role gets added before patching the others. (race condition part)

As a solution I propose that you use `GuildMember#setRoles` because you want to add and remove roles at the same time.
Easiest way would probably to make a set of the current role id's and then remove and add as you wish. Before passing it to setRoles simply spread it.

Small example:
```js
const roles = new Set(member.roles.keyArray());
roles.add('someRoleId');
roles.delete('someOtherRoleId');
member.setRoles([...roles]);
```

And as a side note, which is not really relevant to your current issue, but could be your next:
`GuildMember#removeRoles` takes an array or collection of role ids or role objects.
Passing a single string will just be ignored duo the way the method iterates the string.

**Comment by MinnDevelopment** [comment]
If that is the case the documentation of GuildMember#addRoles and GuildMember#removeRoles can be improved to reflect this behaviour and it should recommend using setRoles instead.
