### ISSUE TITLE
guildMemberSpeaking event on client never gets emitted

### ISSUE THREAD

**Issue by Nimmidev** [hydrabolt/discord.js#1993]
**Please describe the problem you are having in as much detail as possible:**
The 'guildMemberSpeaking' on the client class never gets emitted. I have testet it a multiple times, other events are working. 
I also tried to place a console.log("test"); right inside the '_memberSpeakUpdate' function (Guild.js:972) - nothing.

**Include a reproducible code sample here, if possible:**
```js


   bot = new this.DISCORD.Client();
   bot.login({API_KEY});

   _currentGuild = bot.guilds.get("{GUILD_ID}");
   _currentGuild.members.get("{USER_ID}").client.on("guildMemberSpeaking", (member, bool) => {
      console.log(member, bool);
   });
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: v8.6.0
- Operating system: Win 10 x64
- Priority this issue should have – please be realistic and elaborate if possible: middle-high priority

**Comment by aemino** [comment]
First off, you are using an outdated version of discord.js.  Please install 11.2.0 and let us know if this issue is still prevalent.

Secondly, there are a number of stylistic issues with your code.  For one, you should not be saving modules as properties of a class (or whatever you're doing there.)  Simply import discord.js and use the Client export.  Next, you should not be instantiating variables without either a `var/let/const` statement or setting it as a property of a class.  Instantiating variables without a variable declaration causes them to be pushed to the global scope, which is a bad practice.  Finally, I don't know why you are fetching a member only to then grab the `client` property.  The `client` property of any discord.js resource instance is exactly the same as the `bot` variable you define earlier in your code.  I can see the presumed intent--only listening for the event for one member--but that is not achieved using that code.

**Comment by Nimmidev** [comment]
Thanks for your answer and advice. Actually the variables were instantiated with let i just messed up a little bit when coping my code.
I've now updated to version 11.2.0 and changed the code to:
```js
this._bot.on("guildMemberSpeaking", (member, bool) => {
   console.log(member, bool);
});
```

but it is still not working.

**Comment by robflop** [comment]
I've just tried this with the following sample code on version 11.2.0 (42c195c)

```js
client.on('guildMemberSpeaking', (member, speaking) => {
	console.log(member, speaking);
});
```

and the output was: ![](https://i.robflop.me/5q2Ag.png) when I started and stopped speaking.

What exactly are you doing when trying to trigger the update? I got myself and my bot in a voice channel and then started and stopped speaking myself, which worked and was logged on the bot as seen above.

**Comment by Nimmidev** [comment]
Hm, it doesn't work. I made a new project with the newest Version of discord.js but i dont get any output. stragen :/

**Comment by SpaceEEC** [comment]
Since you never stated it: Is the bot actually connected to a voice channel in the guild?

**Comment by Nimmidev** [comment]
Hmm, i completely reinstalled node and now it is working. Strange, sry fro the inconvenience.
