### ISSUE TITLE
Wrong Node.js minimum version on the documentation website

### ISSUE THREAD

**Issue by InventivetalentDev** [hydrabolt/discord.js#1998]
The official documentation website states an older minimum requirement for the NodeJS version - 6.0.0, while GitHub states 8.0.0 as the minimum.   

![](https://i.inventivetalent.org/2017/10/02/db72f643f4_chrome.png)  

![](https://i.inventivetalent.org/2017/10/02/466fdb1b07_chrome.png)

**Comment by KingDGrizzle** [comment]
Cause the wiki defaults to stable (11.2)
Github defaults to master (12.0)

Master needs node 8+
11.2 needs node 6+

**Comment by devsnek** [comment]
for posterity:
![](https://gc.gy/5.png)

**Comment by InventivetalentDev** [comment]
Well, some info about that on the main page would be nice though. I spent the last 2 days trying to figure out why I can't get audio output to work - updated node to 8.0.0+ and it's working now.

**Comment by iCrawl** [comment]
Switching branches on the docs works, as mentioned above.
But additionally there is also an issue open about it #1386.

I'm not going to say you wasted 48h "trying" to find info about it, but it was pretty much in front of your eyes. Also considering if you go to the repo itself via https://github.com/hydrabolt/discord.js and just scroll a "bit" down, you can see it too.

We aren't going to put it on the stable docs though, it doesn't affect 11.2 at all, which is why it shouldn't be on there.

**Comment by InventivetalentDev** [comment]
I just kinda expected to have something like a newer node version documented in the [*documentation*](https://discord.js.org/#/docs/main/stable/general/welcome), if it's required for the features documented there to work properly.  

Since - as I mentioned - the audio playback, for which I used the [documentation ](https://discord.js.org/#/docs/main/stable/general/welcome), only worked after updating node, which was in turn not mentioned in that documentation but somewhere on github. Just to make clear how confusing this can be...

**Comment by iCrawl** [comment]
It *is* mentioned in the *documentation*.

You were simply on the wrong branch. If you go here https://discord.js.org/#/docs/main/master/general/welcome
You can see that it is correctly showing. Master/v12/Indev is a development version, it won't show up as the "first" thing when you visit the docs because the majority of people use stable, since as the name implies it, it's stable.

**Comment by InventivetalentDev** [comment]
@iCrawl Thanks! Got it.

**Comment by InventivetalentDev** [comment]
Oh, I'm not even using v12 btw. I'm using v11.2, which - apparently - only needs Node v6, however it only worked properly after updating node to v8...
