### ISSUE TITLE
[Feature] Add "emitOnAllReady" to sharding manager

### ISSUE THREAD

**Issue by PassTheMayo** [hydrabolt/discord.js#2031]
**Please describe the problem you are having in as much detail as possible:**
I would like to suggest a feature on the sharding manager. If you put "emitOnAllReady: true" to the sharding manager options, then the ready event won't be emitted on all shards until the client on every shard is ready. This would be very helpful because if you use "bot.shard.broadcastEval" in your ready event, it would throw an error if all shards aren't ready. This feature would fix that and make sure all clients are synced.

**Include a reproducible code sample here, if possible:**
Nothing to show for here.

**Further details:**

- Priority this issue should have – please be realistic and elaborate if possible: Low

**Comment by iamhansen** [comment]
+1

**Comment by DiscordDonut** [comment]
Temp fix: Check if the shard thats loading is the last shard, if it is, put a setTimeout to give it enough time to boot and be ready, then BroadcastEval on the last shard in the setTimeout.

**Comment by iCrawl** [comment]
Emitting ready only when all shards are up and running seems like a super edge-case and very bad.

It may sound nice in theory for your use-case, but its pretty much the worst thing you could do in any other case.

**Comment by pedall** [comment]
What also works is to block the message event as long not all shards are ready. That’s how I do it.

**Comment by iCrawl** [comment]
But what's the point of that? There is almost no reason to wait for another shard to "resume" execution.

Each shard sits on its own servers, they don't overlap. Simply blocking everything until all shards are ready is not efficient and serves barely any purpose. If you *really* do that, you should think of other ways.

**Comment by appellation** [comment]
The `ready` event should signify when the client is ready.  Modifying it to depend on the state of other shards is a bad.

What error occurs when attempting to `broadcastEval` before all shards are ready?  I see no indication that discord.js is bugged in this area.

Whatever you're attempting to do can probably already be accomplished in a much simpler way.  I'm imagining the only use-case for this would be notifying a specific channel that the client is ready, which can be easily solved by using a webhook (probably preferred, since you don't have to worry about client connectivity) or just waiting until the shard with the relevant channel goes online.

**Comment by pedall** [comment]
well I have a startup routine that fetches data from all shards and compares to the db, after all shards are going ready. After that each shard loads it caches. I do this since I want some information to be shared in all shards. And I didn’t find a better solution that far since I’m pretty new to NodeJS :P

**Comment by PassTheMayo** [comment]
@appellation There is no bug, as I stated. It simply gives an error that states "Still spawning shards" which means that not all shards are ready. I think this is a great idea, and would be very helpful, because shards may rely on other shards, and this would solve that issue.

**Comment by appellation** [comment]
Shards should never rely on other shards.

**Comment by PassTheMayo** [comment]
@appellation It can, especially if you are making a dashboard which requires getting data across different shards. If one shard isn't ready and someone makes a request to edit a setting within the dashboard, it may not be ready, and may crash the bot or completely break something.

**Comment by iCrawl** [comment]
I still think this isn't a feasible solution to the issue and rather a "hack".

There's other ways to achieve what you are doing, whether that be through pushing data whenever its ready via a websocket or other means. The proposed solution is also very bad for big bots with more than 50 shards. It would mean the ready event is delayed by a LOT.
So this seems like its not even thought through entirely and just there to solve "your" issue at the moment.

**Comment by PassTheMayo** [comment]
Am I suppose to provide any more information? This is basically all I can explain... This would be very helpful, and 2 people in a discord server I'm in woulda like this to be added.

**Comment by appellation** [comment]
I can assure you that whatever you're doing can also be done in a more performant and fault-tolerant manner that does not require all shards to be ready.

> someone makes a request to edit a setting within the dashboard

This should not require the bot to be online at all.

**Comment by victionn** [comment]
Depends if the provider is inside the client or not. Since some of the functions could rely on the client to actually work within the dash

**Comment by appellation** [comment]
If that is the case, you are doing it wrong.

**Comment by victionn** [comment]
eh.

**Comment by iCrawl** [comment]
You can most certainly connect to a database without your provider.

Anyway, this is getting wayyyy off-topic. There is ways to do any of that in a more clear and abstracted way than what is being proposed.
And if that proposal doesn't change in some kind of way, I see this only being rejected. Because we can not only think about the little bots that do 2-5 shards. People with 50+ shards will attempt to use it, and that's just bad behavior and would be reckless for us to implement.

**Comment by Lewdcario** [comment]
Seems to be rather dead, so closing this.
