### ISSUE TITLE
[Feature] Add "reactionRemove/unCollect" event to msg.ReactionCollector()

### ISSUE THREAD

**Issue by Luminaire117** [hydrabolt/discord.js#2056]
**Please describe the problem you are having in as much detail as possible:**

I'd like to suggest adding an event on a reactionCollector to track un-collects (emitted when someone removes a reaction to the message) as well. Right now the only events are collect, end, and dispose (in v12). Dispose is great but only works when the reaction is completely removed, I think it would be useful to have an event for when a user un-reacts but there are still others with the same reaction.

- Priority this issue should have – please be realistic and elaborate if possible: low

**Comment by Keswiik** [comment]
@iCrawl 
I've got a janky version of this working locally, but a few questions before I try to make this into something worth PRing:

1. Should this be specific to reaction collectors, or implemented in all collectors?
2. In the case something is uncollected, but _also_ needs disposed, should both events be emitted, or just the dispose event?

**Comment by appellation** [comment]
This is something that could only be implemented for reaction collectors.  The only reason this issue exists is because the `Collector` class collects `MessageReactions` which are keyed by emoji not emoji *and* user.  This is due to the nature of message reactions in discord.js, and is intended.

I see no reason why event emission should be conditional upon whether another event would be emitted.  Typically, users listen to one event specifically for the information it provides; altering that behaviour in consideration of another event seems like a very bad idea.

**Comment by Keswiik** [comment]
^ This was more or less my opinion as well, but I thought I should get some clarification before doing anything.

**Comment by Luminaire117** [comment]
Ya sorry if I was confusing, adding it to reaction collectors is exactly what I was suggesting. Thanks!
