### ISSUE TITLE
User Block List for OAuth Bot [question]

### ISSUE THREAD

**Issue by bdistin** [hydrabolt/discord.js#283]
Firstly, I am not aware if Discord allows bots to have friends/blocks; but if they do I cannot find reference of either "friend" or "block" in the [read the docs](https://discordjs.readthedocs.org/en/latest/index.html).

Can a user be added to a bot's block list? If so, what would the syntax be for doing so?

**Backstory:** *I have a malicious user trying to hack/crash my bot. While yes, I has led to several bug fixes, I am tired of this user attacking my bot. I know I can hardcode against that user; but I am hoping there might be something existing and a little easier to manage. (especially if they make alts)*

**Comment by hydrabolt** [comment]
Bots can't friend users, but I don't know for sure if they can block users. I'll look into it.

**Comment by meew0** [comment]
Bot's can't block users because blocking is fundamentally tied to the friends list. Even if bots could block, they'd still receive the message (Discord just displays blocked messages differently). If you don't want to hardcode the ID, you can for example add a dynamic blocklist to your bot that lets you block and unblock users on the fly.

**Comment by bdistin** [comment]
Thanks for looking into this!
