### ISSUE TITLE
Recommended Library?

### ISSUE THREAD

**Issue by ChrisTalman** [hydrabolt/discord.js#307]
Discord maintains a list of [recommended libraries](https://discordapp.com/developers/docs/topics/libraries) 'deemed to work appropriately with [the Discord] API'.

Will discord.js be included in this in the future?

**Comment by BrunoMoreira991** [comment]
Who said it isn't already? https://github.com/hammerandchisel/discord-api-docs/commit/459ff309b236daef4b14477babfbd4ef085d6cc8

**Comment by ChrisTalman** [comment]
@BrunoMoreira991 Well, it is currently not included in the published list.

**Comment by meew0** [comment]
It isn't included in the published list because when the recommended list was compiled, discord.js didn't meet the requirements (mostly a certain standard to 429 handling). It will be included in the published list in a future docs update, as the standards are fulfilled now - it's perfectly good to use.

**Comment by abalabahaha** [comment]
Basically, Discord Devs are stalling and there's nothing we can do but wait.

The library is compliant enough.
