### ISSUE TITLE
InternalClient#updateChannel fails on text channels [indev]

### ISSUE THREAD

**Issue by meishuu** [hydrabolt/discord.js#404]
This is due to [a line that tries to convert bitrate](https://github.com/hydrabolt/discord.js/blob/636a095/src/Client/InternalClient.js#L1372):

```js
data.bitrate *= 1000; // convert to bits before sending
```

For text channels, this turns `data.bitrate` from `undefined` into `NaN` which the API doesn't like.

I've made this an issue instead of a PR because we could:

1. Split into `updateTextChannel` and `updateVoiceChannel` so we don't even bother sending bitrate and user limit for text channels.

2. Make the text vs voice distinction as a check in `updateChannel`.

3. Just hack on a `if (typeof data.bitrate !== 'undefined')` or other similar check.

I'll let someone else decide.

(On this note, I'm a little surprised it gets this far instead of failing at the range checks for `user_limit` and `bitrate`.)

**Comment by GexoXYZ** [comment]
I'm for 2.

**Comment by roncli** [comment]
The issue is a bit deeper than this.  When the call to updateChannel comes back, it is saving the bitrate of NaN back to the cache, so subsequent calls to updateChannel will fail.

I have worked around this by removing the bitrate from the channel in the cache prior to making the updateChannel call.
