### ISSUE TITLE
How do I get my bot to mention groups

### ISSUE THREAD

**Issue by Techmo3014** [hydrabolt/discord.js#459]
```
var Discord = require("discord.js");

var bot = new Discord.Client();

bot.on("message", function (message)
{
	var input = message.content.toUpperCase();
	
	if(input === "HELP!")
	{
		bot.sendMessage(message, "@admins are on the way!");
	}
	if(input === "PING")
    {
	    bot.sendMessage(message, "Pong!");
    }
    if(input === "WHO MADE SHADOWBOT?")

	{
		bot.sendMessage(message, "@Techmo3014#7140 made me.")
	}
	
});

bot.loginWithToken("my token");
```

That is my code, could any of you edit it so the @admins and @techmo3014#7140 work?

**Comment by GexoXYZ** [comment]
In Discord in general you can mention people with `<@ID>` and *mentionable* roles with `<@&ID>`. Discord.js has helper functions for that though, so `<userObject>.mention()` and `<roleObject>.mention()` works. Even better, these objects `.toString()` will return that function, and node calls `.toString()` on anything that's interpreted as a string!

So to answer your question you'd first have to get the objects and then you can simply insert them in your string:

```js
var Discord = require("discord.js");

var bot = new Discord.Client();

bot.on("message", function (message)
{
    var input = message.content.toUpperCase();

    if(input === "HELP!")
    {
      	let adminRoleObject = msg.server.roles.get('name', 'admins');
        bot.sendMessage(message, `${adminRoleObject} are on the way!`);
    }
    if(input === "PING")
    {
        bot.sendMessage(message, "Pong!");
    }
    if(input === "WHO MADE SHADOWBOT?")

    {
        let ownerUserObject = msg.server.members.get('name', 'Techmo3014');
        bot.sendMessage(message, `${ownerUserObject} made me.`);
    }

});

bot.loginWithToken("my token");
```

(Although I'd recommend you to use ID's instead of names, especially for the user)

**Comment by Techmo3014** [comment]
Thank you @GexoXYZ

**Comment by Techmo3014** [comment]
Doesn't work :/

**Comment by Techmo3014** [comment]
Why doesn't it work

**Comment by GexoXYZ** [comment]
https://discord.gg/S8mDK Give us a visit :eyes:

**Comment by GreenBayRules** [comment]
message.server.member returns for me "Cannot get member of undefined"

**Comment by SpaceEEC** [comment]
This issue is over a year old.

Also like the label suggests, please use our [Discord server](https://discord.gg/bRCvFy9) to ask questions.
The issue tracker is only for bug reports and enhancement suggestions.
