### ISSUE TITLE
Mentioning someone in a message

### ISSUE THREAD

**Issue by CoodleNoodle** [hydrabolt/discord.js#578]
k so, I want to @ message myself with a bot. 
Like say I tell, if(input === "!CallCoodle") 
I want the bot to mention me"@Coodle Someone is calling you"

**Comment by FrankenMan** [comment]
pls

**Comment by hydrabolt** [comment]
![image](https://cloud.githubusercontent.com/assets/10330923/18178723/697ee846-7077-11e6-9d8f-79f792908db8.png)

![image](https://cloud.githubusercontent.com/assets/10330923/18178708/5e967b1a-7077-11e6-8524-bdcb54814c98.png)

**Comment by hydrabolt** [comment]
read the docs

**Comment by eslachance** [comment]
Coodle, this would be a reply: `bot.reply(message, "Someone is calling you");`
Please read the [Discord.js documentation](http://discordjs.readthedocs.io/en/latest/) instead of asking in a github issue for help. Alternatively, join [Discord-API](https://discord.gg/KhrVx) if you have questions. 

You should also probably check the [Discord.JS Bot Guide](https://www.gitbook.com/read/book/eslachance/discord-js-bot-guide) for some... guidance.

**Comment by CoodleNoodle** [comment]
I'm extremely sorry to waste your time, I had just realized by syntax wasn't working because of a ";" once again, I'm very sorry
