### ISSUE TITLE
Add support for date in ChannelLogsQueryOptions

### ISSUE THREAD

**Issue by timhwang21** [hydrabolt/discord.js#639]
http://hydrabolt.github.io/discord.js/#!/docs/tag/master/typedef/ChannelLogsQueryOptions

It would be nice if I could pass `{ beforeDate: date }` as an option. My use case is creating a sweeper to delete all messages over x hours old. Date could be a ISO string or a moment js object, whichever works better. 

Is there a better way to accomplish this already? Thank you, really enjoying using this so far!

**Comment by timhwang21** [comment]
Also, I was wondering how performant querying channel logs is. My current solution sets up a messageCollector every hour that captures all messages, then sets up a cron job to delete the collection after 48 hours. The obvious limitation is that the messages to be deleted are in memory, but I don't have to query the entire message history every hour. Thanks!

**Comment by GexoXYZ** [comment]
The `ChannelLogsQueryOptions` are just taken straight [from the official API](https://discordapp.com/developers/docs/resources/channel#json-params). To implement a `beforeDate` the lib would have to call `getMessages` recursively until a message sent at `beforeDate` was reached, which is very impractical.

Also querying channel logs would probably be a lot more performant for you, because you don't have to store all the messages that way as you already said. Some people delete 1000 messages in 10 seconds which shouldn't be a problem. You can currently fetch 100 messages/second so you should be good to go.

**Comment by timhwang21** [comment]
Surely a binary search implementation would work? The messages are ordered after all. (bsearch for message with date closest to `beforeDate`, get id, then do query for `{ before: id }`)

Regardless, thanks for the clarification. Would you recommend fetching messages 100 at a time and deleting until I arrive at my time cutoff? (Not in a position to test atm -- do you know if the messages are returned most recently first or least recently first?) Thank you!
