### ISSUE TITLE
Role.edit({position: 1}) and Role.setPosition(1) don't seem to work

### ISSUE THREAD

**Issue by Tyler0130** [hydrabolt/discord.js#751]
`role.edit({position: 2})` and `role.setPosition(2)` both don't seem to move the role to the correct position.
I'm not receiving any errors and my code acts if the position was changed, even though it hasn't.

**Comment by kjsalexander** [comment]
I've been running into this issue as well, for both v9 and v8.

**Comment by Gawdl3y** [comment]
This appears to be a problem with the API. I have no idea why it isn't working, but I can, in fact, verify that it's not. 👍

**Comment by Gawdl3y** [comment]
From what I hear, you must use the bulk update endpoint to edit the positions of roles or channels.

**Comment by hydrabolt** [comment]
This has been fixed in 0c4a4023cef4ee37f521980277307d96fdc64520. The usage has not changed; `role.setPosition(4)` is still valid and now works. Additionally, `Guild.setRolePosition(roleOrRoleID, position)` has been added.

However, as @Gawdl3y has said, the bulk update endpoint means `Role.edit({ position: 1 });` will not work as `Role.edit` uses a different endpoint to the one that is required for setting the position of a role. 

This update will be released in the version 10 update.
