### ISSUE TITLE
nickname undefined + userUpdate not being fired

### ISSUE THREAD

**Issue by WilliamVenner** [hydrabolt/discord.js#758]
Hi,

I have this code:

```javascript
gmodstore.bot.on("userUpdate",function(oldUser,newUser) {
	gmodstore.database.query("INSERT INTO `bot_discordids` (`id`,`username`,`nickname`) VALUES(?,?,?) ON DUPLICATE KEY UPDATE `id`=?, `username`=?, `nickname`=?",[newUser.id,newUser.username,newUser.nickname,newUser.id,newUser.username,newUser.nickname]);
});

[..]

gmodstore.bot.on("ready",function() {
	
	gmodstore.guild = gmodstore.bot.guilds.array();
	for (var i=0;i < gmodstore.guild.length;i++) {
		if (gmodstore.guild[i].id == "191312474954268672") { // bot only used on one server
			gmodstore.guild = gmodstore.guild[i];
			gmodstore.users = gmodstore.guild.members.array();
			for (var i=0;i < gmodstore.users.length;i++) {
				gmodstore.database.query("INSERT INTO `bot_discordids` (`id`,`username`,`nickname`) VALUES(?,?,?) ON DUPLICATE KEY UPDATE `id`=?, `username`=?, `nickname`=?",[gmodstore.users[i].id,gmodstore.users[i].user.username,gmodstore.users[i].nickname || gmodstore.users[i].user.username,gmodstore.users[i].id,gmodstore.users[i].user.username,gmodstore.users[i].nickname || gmodstore.users[i].user.username]);
			}
		}
	}

[..]
```

To put it simply, `userUpdate` isn't being fired nor are nicknames working. EVERY user has their nickname set to `undefined`, including mine (I really have a nickname, along with many others in the server).

I have updated and the problem still exists.

Is there something I'm doing wrong?

Thanks

**Comment by GusCaplan** [comment]
are you on v8?

**Comment by WilliamVenner** [comment]
`.array()` _converts_ them from a collection to an array.

And I am using GuildMembers. `gmodstore.guild.members` returns GuildMembers, not Users. `username` is in User, but `nickname` is only in GuildMembers. To access the username I do `.user.username` and nickname simply `.nickname`, but it's always undefined.

Upon using `console.log` on `gmodstore.users[i]`, it shows that `nickname` is literally set to undefined.

I'm not sure what you mean by "are you on v8?"; I'm simply installing it from npm.

**Comment by Gawdl3y** [comment]
- `userUpdate` only fires for username/avatar changes, IIRC.
- `User`s do not have a `nickname` property, only `GuildMember`s do. Nicknames are guild-specific.
- A `GuildMember`'s `nickname` is only set if they actually have one.
- `Collection`s extend `Map`, so you can use any methods that those have. [Map docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)
- Converting the collections to arrays is a horribly inefficient way to iterate over them. Since they are maps, you can iterate over them with `for(const member of guild.members.values())`, for example.
- You don't even need to iterate over the guilds if you're only using one; just use `gmodstore.bot.guilds.get('191312474954268672')` to get that single guild.

**Comment by GusCaplan** [comment]
what a bunch of spaghetti code

**Comment by WilliamVenner** [comment]
sorry for being a beginner @GusCaplan

again, I am _not_ using `User`s. I'm iterating through Guild.members which on the docs says it's a collection of `GuildMember`s. I also stated that I, and many others, do have nicknames, yet it's set to `undefined`. It even shows `nickname` as `undefined` when `console.log`ing the `GuildMember`.

Thank you for the other information.
