### ISSUE TITLE
"seek" stream option takes several seconds for song to resume.

### ISSUE THREAD

**Issue by Trismirite** [hydrabolt/discord.js#867]
After setting the seek option of my stream to about 20 minutes (1200 seconds), it has an unusual nearly 30 second pause until it plays the stream. This doesn't really happen with smaller numbers, but it's noticeable. I'm creating the stream dispatcher with `const dispatcher = queue.connection.playStream(stream, {seek: seek})`, as normal. I'm on Discord.JS version 10.0.1.

**Comment by iCrawl** [comment]
I'm assuming that's because a video never gets fully buffered, so you cannot just instantly skip to any position you want.
Assuming it takes around 20~30sec it would make sense that it buffers the specific part you skipped to.

**Comment by Gawdl3y** [comment]
If I were to guess, this is unavoidable. If I'm correct, the stream is not fully buffered, and seeking just makes the stream get processed as quickly as possible until that amount of audio time has been skipped.
I may very well be incorrect on this, however. Leaving this open until someone with more knowledge comments.

**Comment by R3alCl0ud** [comment]
As the one who added the seek parameter in the first-place for v9, this issue is unavoidable as where the code is for seeking to the location in the audio stream is part of the direct call to ffmpeg/libav to encode the audio in opus format, meaning this is an issue with ffmpeg/libav that cannot be fixed by changing code in discord.js

**Comment by hydrabolt** [comment]
Looks like there isn't much we can do about this issue, sorry!
